language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - pytest

deploy:
    provider: pypi
    user: "your user"
    password: "your password (replace with `travis encrypt 'your password' --add deploy.password`)"
    on:
        - branch: master
        - tags: true
